"""LLM 提示词库（按主题拆分为子模块；spec 003 T603）。

config.py 底部再导出本包全部常量，`from config import X` 与 `from prompts import X` 均可用。
"""

from .analysis import (  # noqa: F401
    ANALYSIS_SYSTEM_PROMPT,
    GRILLING_PROMPT,
    VALIDATION_SYSTEM_PROMPT,
    VALIDATION_PROMPT_TEMPLATE,
    TITLE_SUMMARIZE_PROMPT,
)

from .ontology_generate import (  # noqa: F401
    ONTOLOGY_GENERATE_SYSTEM_PROMPT,
    ONTOLOGY_GENERATE_PROMPT_TEMPLATE,
)

from .data_engine import (  # noqa: F401
    MAPPING_ANALYSIS_SYSTEM_PROMPT,
    MAPPING_ANALYSIS_PROMPT,
    ALIGNMENT_SYSTEM_PROMPT,
    ALIGNMENT_PROMPT,
    TARGET_PARSE_SYSTEM_PROMPT,
    TARGET_PARSE_PROMPT,
)

from .function_code import (  # noqa: F401
    FUNCTION_CODE_SYSTEM_PROMPT,
    FUNCTION_CODE_PROMPT,
)

from .rule_generate import (  # noqa: F401
    RULE_GENERATE_SYSTEM_PROMPT,
    RULE_GENERATE_PROMPT,
)

from .skill_generate import (  # noqa: F401
    SKILL_GENERATE_SYSTEM_PROMPT,
    SKILL_GENERATE_PROMPT,
)

__all__ = [
    "ANALYSIS_SYSTEM_PROMPT",
    "GRILLING_PROMPT",
    "VALIDATION_SYSTEM_PROMPT",
    "VALIDATION_PROMPT_TEMPLATE",
    "TITLE_SUMMARIZE_PROMPT",
    "ONTOLOGY_GENERATE_SYSTEM_PROMPT",
    "ONTOLOGY_GENERATE_PROMPT_TEMPLATE",
    "MAPPING_ANALYSIS_SYSTEM_PROMPT",
    "MAPPING_ANALYSIS_PROMPT",
    "ALIGNMENT_SYSTEM_PROMPT",
    "ALIGNMENT_PROMPT",
    "TARGET_PARSE_SYSTEM_PROMPT",
    "TARGET_PARSE_PROMPT",
    "FUNCTION_CODE_SYSTEM_PROMPT",
    "FUNCTION_CODE_PROMPT",
    "RULE_GENERATE_SYSTEM_PROMPT",
    "RULE_GENERATE_PROMPT",
    "SKILL_GENERATE_SYSTEM_PROMPT",
    "SKILL_GENERATE_PROMPT",
]
